training:
  batch_size: 1024
  epsilon: 8/255
  alpha: 2/255
  num_iter: 10
paths:
  weights_dir: ./weights
  datasets_dir: ./datasets
  results_dir: ./results
  logs_dir: ./logs 
  The  training  section contains the hyperparameters for the training process. The  paths  section contains the paths to the directories where the weights, datasets, results, and logs will be stored.